//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarGame.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        public string LevelPath { get; set; }

        public string ImportPath { get; set; }

        public string ImagePlayer { get; set; }
        public string ImageMissile { get; set; }
        public string ImageMud { get; set; }
        public string ImageTree { get; set; }
        public string ImageMine { get; set; }
        public string ImageSandbag { get; set; }
        public string ImageFinish { get; set; }
        public string ImageExplosion { get; set; }
        public string ImageTransparent { get; set; }
    }
}
